create table block (id bigint not null auto_increment, name varchar(255), map_id bigint, type_id bigint, primary key (id)) engine=InnoDB;
create table block_location (block_id bigint not null, point_id bigint not null, primary key (block_id, point_id)) engine=InnoDB;
create table block_path (block_id bigint not null, point_id bigint not null, primary key (block_id, point_id)) engine=InnoDB;
create table block_point (block_id bigint not null, point_id bigint not null, primary key (block_id, point_id)) engine=InnoDB;
create table block_miscellaneous (id bigint not null auto_increment, `key` varchar(255), `value` varchar(255), block_id bigint, primary key (id)) engine=InnoDB;
create table block_type (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table control_point (id bigint not null auto_increment, x decimal(19,2), y decimal(19,2), path_id bigint, primary key (id)) engine=InnoDB;
create table drive_order (id bigint not null auto_increment, costs integer, operation_id bigint, status_id bigint, target_id bigint, torder_id bigint, primary key (id)) engine=InnoDB;
create table drive_order_route (id bigint not null auto_increment, destination_id bigint, dorder_id bigint, path_id bigint, primary key (id)) engine=InnoDB;
create table drive_order_status (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table location (id bigint not null auto_increment, image longblob, name varchar(255), x_position decimal(19,2), y_position decimal(19,2), map_id bigint, type_id bigint, primary key (id)) engine=InnoDB;
create table location_miscellaneous (id bigint not null auto_increment, `key` varchar(255), `value` varchar(255), location_id bigint, primary key (id)) engine=InnoDB;
create table location_type (id bigint not null auto_increment, image longblob, name varchar(255), primary key (id)) engine=InnoDB;
create table location_type_action (id bigint not null auto_increment, name varchar(255), type_id bigint, primary key (id)) engine=InnoDB;
create table location_type_miscellaneous (id bigint not null auto_increment, `key` varchar(255), `value` varchar(255), type_id bigint, primary key (id)) engine=InnoDB;
create table map (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table miscellaneous (id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table path (id bigint not null auto_increment, cost integer, disabled bit, length decimal(19,2), max_reverse_velocity decimal(19,2), max_velocity decimal(19,2), name varchar(255), end_id bigint, map_id bigint, start_id bigint, type_id bigint, primary key (id)) engine=InnoDB;
create table path_miscellaneous (id bigint not null auto_increment, `key` varchar(255), `value` varchar(255), path_id bigint, primary key (id)) engine=InnoDB;
create table path_type (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table point (id bigint not null auto_increment, angle decimal(19,2), name varchar(255), x_position decimal(19,2), y_position decimal(19,2), map_id bigint, type_id bigint, primary key (id)) engine=InnoDB;
create table point_miscellaneous (id bigint not null auto_increment, `key` varchar(255), `value` varchar(255), point_id bigint, primary key (id)) engine=InnoDB;
create table point_type (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table transport_order (id bigint not null auto_increment, created_time datetime, deadline_time datetime, finished_time datetime, name varchar(255), category_id bigint, executing_vehicle_id bigint, intended_vehicle_id bigint, map_id bigint, source_id bigint, status_id bigint, target_id bigint, primary key (id)) engine=InnoDB;
create table transport_order_category (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table transport_order_event (id bigint not null auto_increment, description varchar(255), time datetime, order_id bigint, primary key (id)) engine=InnoDB;
create table transport_order_status (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table vehicle (id bigint not null auto_increment, current_energy decimal(19,2), energy_critical decimal(19,2), energy_full decimal(19,2), energy_good decimal(19,2), energy_sufficient decimal(19,2), length decimal(19,2), loaded bit, max_reverse_velocity decimal(19,2), max_velocity decimal(19,2), name varchar(255), orientation varchar(255), position varchar(255), processing_state varchar(255), width decimal(19,2), current_order_id bigint, current_point_id bigint, map_id bigint, next_point_id bigint, order_category_id bigint, state_id bigint, primary key (id)) engine=InnoDB;
create table vehicle_miscellaneous (id bigint not null auto_increment, `key` varchar(255), `value` varchar(255), vehicle_id bigint, primary key (id)) engine=InnoDB;
create table vehicle_state (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
alter table block add constraint FKhii2h0qi2gdow9tyq8kns80mp foreign key (map_id) references map (id);
alter table block add constraint FKapusmbsce12auf8n4llw7frv5 foreign key (type_id) references block_type (id);
alter table block_location add constraint FKsn22frc0hpxckx8qmciiul4dn foreign key (point_id) references location (id);
alter table block_location add constraint FK7a8f49ubmeotekke31b9j7lc5 foreign key (block_id) references block (id);
alter table block_path add constraint FKtdry543jepwbt1mdh50104as9 foreign key (point_id) references path (id);
alter table block_path add constraint FKh3uleq86nmcd5ia8kx48qctqv foreign key (block_id) references block (id);
alter table block_point add constraint FK8a9pmedkjl8drvxwyeqoiu77s foreign key (point_id) references point (id);
alter table block_point add constraint FKmu6kk6avv2g6yo01f3ytwwlxu foreign key (block_id) references block (id);
alter table block_miscellaneous add constraint FKp6prhidamjjsp9twvgn56co2c foreign key (block_id) references block (id);
alter table control_point add constraint FKlyv5keh8dj2nawyfc0j069ma foreign key (path_id) references path (id);
alter table drive_order add constraint FK8npo8x1fsspcol1sog3idv5k4 foreign key (operation_id) references location_type_action (id);
alter table drive_order add constraint FKtguxyafcsjt89vslgthyhdoaf foreign key (status_id) references drive_order_status (id);
alter table drive_order add constraint FK58x3vh7ug31vc3d15bv42p2q9 foreign key (target_id) references location (id);
alter table drive_order add constraint FKlx2nd7r8epu441e44u6vb8s86 foreign key (torder_id) references transport_order (id);
alter table drive_order_route add constraint FKd1n3h6otenlpyjm7xoshqryms foreign key (destination_id) references point (id);
alter table drive_order_route add constraint FK4ynin7btyjhgyl844y961q3yf foreign key (dorder_id) references drive_order (id);
alter table drive_order_route add constraint FKea9c96xb4xwowk5xvfkg51ut5 foreign key (path_id) references path (id);
alter table location add constraint FKi8ocynbgl0jaj2mc80rfpmh3y foreign key (map_id) references map (id);
alter table location add constraint FK3l2oelpu05dyarlppuv42vu0p foreign key (type_id) references location_type (id);
alter table location_miscellaneous add constraint FKpesttk27g2mpma4drv6a2hnw2 foreign key (location_id) references location (id);
alter table location_type_action add constraint FKrtj76g3o4r92p6jjw2dekyi85 foreign key (type_id) references location_type (id);
alter table location_type_miscellaneous add constraint FKdjucpuc9dvjosrsfy4kpe3cu6 foreign key (type_id) references location_type (id);
alter table path add constraint FKt2ug6khsco68nxhw3lj30di3u foreign key (end_id) references point (id);
alter table path add constraint FK7covdrmmh4dd7cn2204q28bdu foreign key (map_id) references map (id);
alter table path add constraint FKai5wobmy1l7tmj4h5t7s085kv foreign key (start_id) references point (id);
alter table path add constraint FK5oyp5nk9tgwxlnhkx6u5s6shx foreign key (type_id) references path_type (id);
alter table path_miscellaneous add constraint FKg6edhae3w0xuuvgdr7y2rhxt4 foreign key (path_id) references path (id);
alter table point add constraint FK73idpa6y8rvqrmh4md6m5kexx foreign key (map_id) references map (id);
alter table point add constraint FKpcborndmrg5i42ky7qo7ixtfc foreign key (type_id) references point_type (id);
alter table point_miscellaneous add constraint FKki62xst32gb03fayx391lgnsf foreign key (point_id) references point (id);
alter table transport_order add constraint FK6k4lkoeump3iadx90amnm18sa foreign key (category_id) references transport_order_category (id);
alter table transport_order add constraint FKiwbc1wt410go7mpr97v5i7aws foreign key (executing_vehicle_id) references vehicle (id);
alter table transport_order add constraint FKkxxf29rqe2uc542874ot319gv foreign key (intended_vehicle_id) references vehicle (id);
alter table transport_order add constraint FKfmhhyhh3h042297dsvg9xyct0 foreign key (map_id) references map (id);
alter table transport_order add constraint FK7piudkymthvi56wa5jukfprb foreign key (source_id) references location (id);
alter table transport_order add constraint FKs4anmnydbln213pwjb3og0vyy foreign key (status_id) references transport_order_status (id);
alter table transport_order add constraint FK97vwdjoketa128paxp99dc4lh foreign key (target_id) references location (id);
alter table transport_order_event add constraint FKr085fxx53iud03o7hayqawc71 foreign key (order_id) references transport_order (id);
alter table vehicle add constraint FK2bkdc1hot9i0wgm4s5i3v6ffo foreign key (current_order_id) references transport_order (id);
alter table vehicle add constraint FKo7gmmvrfjqt3luat4demlaf1n foreign key (current_point_id) references point (id);
alter table vehicle add constraint FK39j4nnpjhtm9ykoi32w6a6qr3 foreign key (map_id) references map (id);
alter table vehicle add constraint FKhit0akpoajfjqqgsfery4qw4l foreign key (next_point_id) references point (id);
alter table vehicle add constraint FK71v3iehgcvd7oekeyd2txnsgc foreign key (order_category_id) references transport_order_category (id);
alter table vehicle add constraint FKbtjm1bn1vtub3wtt85a2qfx86 foreign key (state_id) references vehicle_state (id);
alter table vehicle_miscellaneous add constraint FKjb7fg4dn9jkccbmcjdf5mj8ea foreign key (vehicle_id) references vehicle (id);
